### ISSUE TITLE
关于训练自己数据集问题

### ISSUE THREAD

**Issue by yaoliu0803** [wdhudiekou/IMF#3]
作者您好，关于这篇论文代码有几个问题想要请教：
1.我在您的代码上训练自己的数据集，但是我的数据集格式为RGB和灰度图像，请问如果我想要配准这两种类型的数据，数据预处理该如何进行？
2.我在您的代码中看到，您对彩色可见光的图像的处理是，读取为灰度图像。那我在配准/融合完成后，想将结果转换为彩色RGB图像该如何处理？

**Comment by wdhudiekou** [comment]
感谢您关注我们的工作！您提到的灰度图像是红外图像吗？在配准之前，我们将可见光图像转换为YCbC模式，采用Y通道图像与红外图像进行配准与融合，最后将融合图像与Cb和Cr合并，就得到彩色的融合图像。

**Comment by yaoliu0803** [comment]
感谢您之前的回复！另外想请教一下，如果我想联合训练配准和融合，运行train_reg_co_fusion_sa.py文件，其中的--ir_map参数，传入的应该是原始形变的ir的显著图，还是配准后的ir_reg的显著图？

**Comment by wdhudiekou** [comment]
是配准后的ir_reg的显著图
