### ISSUE TITLE
关于test_reg.py的问题

### ISSUE THREAD

**Issue by 654hhh** [wdhudiekou/IMF#4]
作者你好，请问test_reg.py文件里面的disp是什么？能否去掉？

**Comment by wdhudiekou** [comment]
disp是保存的变形场，可以去掉。

**Comment by rbw2157** [comment]
> disp是保存的变形场，可以去掉。

在输入的时候要求的是输入伪红外   畸变红外  和disp   但是这里作者是用真实红外生成畸变红外获取的disp  真实世界的畸变红外是没有disp的啊  去掉disp 配准没效果

**Comment by rbw2157** [comment]
> 作者你好，请问test_reg.py文件里面的disp是什么？能否去掉？

你去掉的吗  我去掉么效果  你是如何解决这个问题的
