### ISSUE TITLE
Not able to download the pre-train model

### ISSUE THREAD

**Issue by Shreya-3112** [wdhudiekou/IMF#5]
hello, your work is very interesting. I want to test my images on your model, but I cannot download the trained model from the mentioned platform. It would be of great help if you could provide the processed model.

**Comment by wdhudiekou** [comment]
You can download all pre-trained models from this link: https://drive.google.com/drive/folders/1qa_-28_3iZEMpaekU-oyByOiTueKr5q-?usp=drive_link

**Comment by Shreya-3112** [comment]
Thankyou for your quick response.
